FROM docker.io/debian:bookworm-slim

USER root

RUN set -exu \
  && export DEBIAN_FRONTEND=noninteractive \
  && apt-get -yq update \
  && apt-get -yq install \
    bash \
    curl \
    nano \
    wget \
    git \
    python3 \
    python3-venv \
    libgl1 \
    libglib2.0-0 \
    libtcmalloc-minimal4 \
    bc \
    pciutils \
  && apt-get -yq clean

RUN set -exu \
  && addgroup \
    --gid 1000 \
    comfyui \
  && adduser \
    --uid 1000 \
    --ingroup comfyui \
    --disabled-password \
    --gecos comfyui \
    comfyui

# comfyui repo assumed to have been cloned for us
COPY --chown=comfyui:comfyui ./comfyui /home/comfyui/comfyui
COPY ./entrypoint.sh /home/comfyui/entrypoint.sh

USER comfyui
WORKDIR /home/comfyui/comfyui

RUN set -exu \
  && export DEBIAN_FRONTEND=noninteractive \
  && pip install --pre \
      torch \
      torchvision \
      torchaudio \
      --index-url https://download.pytorch.org/whl/nightly/cu128 \
  && pip install -r \
      requirements.txt

WORKDIR /home/comfyui


ENTRYPOINT ["/bin/bash"]
CMD ["/home/comfyui/entrypoint.sh"]
