---
apiVersion: v1
kind: Namespace
metadata:
  name: comfyui

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: comfyui-gpu0
  namespace: comfyui
spec:
  replicas: 1
  selector:
    matchLabels:
      app: comfyui-gpu0
  template:
    metadata:
      labels:
        app: comfyui-gpu0
    spec:
      runtimeClassName: nvidia-cdi
      containers:
      - name: fileeditor
        image: alpine:latest
        command:
        - /bin/sh
        - -c
        - tail -f /dev/null
        volumeMounts:
        - mountPath: "/comfyui-tmpfs"
          name: comfyui-tmpfs
        - mountPath: "/comfyui-data"
          name: application-data
        - mountPath: "/models"
          name: aimodels-image-generation
      - name: comfyui
        env:
        - name: NVIDIA_VISIBLE_DEVICES
          value: all
        - name: NVIDIA_DRIVER_CAPABILITIES
          value: compute,utility
        image: "ghcr.io/thehonker/comfyui:cu128-latest"
        imagePullPolicy: Always
        command:
        - /bin/bash
        - -c
        - >-
          /home/comfyui/entrypoint.sh
          --base-directory /comfyui-data
          --cuda-device 0
          --cuda-malloc
          --disable-auto-launch
          --disable-smart-memory
          --enable-compress-response-body
          --listen 0.0.0.0
          --log-stdout
          --multi-user
          --port 8188
          --preview-method auto
          --temp-directory /comfyui-tmpfs
        ports:
          - name: http
            protocol: TCP
            containerPort: 8188
        volumeMounts:
        - mountPath: "/comfyui-tmpfs"
          name: comfyui-tmpfs
        - mountPath: "/comfyui-data"
          name: application-data
        - mountPath: "/models"
          name: aimodels-image-generation
      volumes:
        - name: comfyui-tmpfs
          emptyDir:
            medium: Memory
        - name: application-data
          persistentVolumeClaim:
            claimName: application-data
        - name: aimodels-image-generation
          persistentVolumeClaim:
            claimName: aimodels-image-generation
